### ISSUE TITLE
Local Preview

### ISSUE THREAD

**Issue by pancetta** [Helmholtz-HiRSE/helmholtz-hirse.github.io#2]
Add a way/guide to run local builds. Then contributors can check their changes before pushing.

**Comment by steffengraber** [comment]
For this we would also have to define a development workflow. My opinion is that working with forks and pull requests like the one here (#1) makes the most sense if several people are to collaborate. Your opinion?

**Comment by pancetta** [comment]
Isn't it just installing ruby, then `bundle install`, then `bundle exec jekyll serve --watch`? I guess it would be good if contributors would have an option to check what they're doing.

**Comment by steffengraber** [comment]
Yes, for the local side, the only thing missing is the installation of the dependencies at the beginning, or how to use the jekyll docker container. But I think that the next necessary step is how to get the content into the git repository. Or should the users not do that at all? Then that should also be described.

**Comment by pancetta** [comment]
So you're saying we should describe the whole workflow: people fork, change, build locally, push, the add a PR.
