### ISSUE TITLE
Add hyphen to my name

### ISSUE THREAD

**Issue by cromeG** [Helmholtz-HiRSE/helmholtz-hirse.github.io#6]
Could you please add an hyphen to my name in the FLEUR members, so that it is Christian-R. instead of Christian R. ?

Thank you. :)

**Comment by pancetta** [comment]
Done [here](https://github.com/Helmholtz-HiRSE/helmholtz-hirse.github.io/commit/e75eb34da805fd07fb452aa13413b19bfad0abe3).

**Comment by cromeG** [comment]
Thx!
